import { createHash, randomUUID } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  REPOSITORY_DIRECTORY,
  timingPassCycle,
  validateBatchManifest,
} from './validate-batch.mjs';

const SCRIPT_DIRECTORY = path.dirname(fileURLToPath(import.meta.url));
const REQUIRED_PASS_IDS = Object.freeze([
  'target-preparation',
  'initial-review',
  'feedback-fixes',
  'final-audit',
  'held-rejected',
]);
const OPTIONAL_PASS_IDS = Object.freeze([
  'post-review-audit',
  'post-review-fixes',
]);
const TIMING_RECORDER_SOURCE = 'timing-recorder-v1';
const LEGACY_TIMING_CONTRACT_VERSION = 'm5-9a-v1';
const M5_10A_TIMING_CONTRACT_VERSION = 'm5-10a-v1';
const M5_10A_PROCESS_REVISION = 'm5-10a-process-correction-v1';
export const CALIBRATION_TIMING_RECORDER_VERSION = 'timing-recorder-v1';
export const CALIBRATION_TIMING_PASS_IDS = Object.freeze([
  'target-preparation',
  'initial-review',
  'feedback-fixes',
  'final-audit',
  'held-rejected',
]);
export const CALIBRATION_TIMING_RECORDING_COMMAND = 'node scripts/batch/record-m5-10a-calibration-timing.mjs';

export class TimingRecordingError extends Error {
  constructor(message, code = 'TIMING_RECORDING_ERROR') {
    super(message);
    this.name = 'TimingRecordingError';
    this.code = code;
  }
}

function fail(message, code = 'TIMING_RECORDING_ERROR') {
  throw new TimingRecordingError(message, code);
}

function requireFeedbackTimestamp(value) {
  if (typeof value !== 'string'
    || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/u.test(value)
    || !Number.isFinite(Date.parse(value))) {
    fail('feedbackReceivedAt must be an ISO-8601 UTC timestamp', 'INVALID_FEEDBACK_TIMESTAMP');
  }
}

function timestampFromClock(now, label = 'now') {
  const value = typeof now === 'function' ? now() : now;
  const date = value === undefined ? new Date() : new Date(value);
  if (!Number.isFinite(date.getTime())) {
    fail(`${label} must be a valid timestamp`, 'INVALID_TIMESTAMP');
  }
  const timestamp = date.toISOString();
  requireFeedbackTimestamp(timestamp);
  return timestamp;
}

function requirePassId(passId) {
  if (![...REQUIRED_PASS_IDS, ...OPTIONAL_PASS_IDS].includes(passId)) {
    fail(`unknown timing pass ${String(passId)}`, 'UNKNOWN_TIMING_PASS');
  }
}

function requireSessionId(sessionId) {
  const value = sessionId ?? randomUUID();
  if (typeof value !== 'string' || !/^[A-Za-z0-9][A-Za-z0-9._:-]*$/u.test(value)) {
    fail('sessionId must be a non-empty recorder session ID', 'INVALID_SESSION_ID');
  }
  return value;
}

function requireUuidSessionId(sessionId, label) {
  if (typeof sessionId !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u.test(sessionId)) {
    fail(`${label} must be a UUIDv4 generated by the timing recorder`, 'TIMING_PROVENANCE_REQUIRED');
  }
  return sessionId;
}

function calibrationTimingProof(recording) {
  const payload = {
    recorder_version: recording.recorder_version,
    recording_source: recording.recording_source,
    recorder_command: recording.recorder_command,
    session_id: recording.session_id,
    clock_source: recording.clock_source,
    recorded_at: recording.recorded_at,
    processed_start_count: recording.processed_start_count,
    passes: recording.passes,
  };
  return createHash('sha256').update(JSON.stringify(payload)).digest('hex');
}

function calibrationTimestamp(now, label) {
  return timestampFromClock(now, label);
}

function finishCalibrationTimingRecording({
  processedStartCount,
  recorderCommand,
  passes,
  sessionId = randomUUID(),
}) {
  const recording = {
    schema_version: '1',
    recorder_version: CALIBRATION_TIMING_RECORDER_VERSION,
    recording_source: CALIBRATION_TIMING_RECORDER_VERSION,
    recorder_command: recorderCommand,
    session_id: sessionId,
    clock_source: 'system-clock',
    recorded_at: calibrationTimestamp(undefined, 'recorded_at'),
    processed_start_count: processedStartCount,
    passes,
  };
  return {
    ...recording,
    recording_proof_sha256: calibrationTimingProof(recording),
  };
}

export function startCalibrationTimingPass({ passId, now } = {}) {
  if (!CALIBRATION_TIMING_PASS_IDS.includes(passId)) {
    fail(`unknown calibration timing pass ${String(passId)}`, 'UNKNOWN_TIMING_PASS');
  }
  return {
    id: passId,
    status: 'in-progress',
    started_at: calibrationTimestamp(now, `${passId}.started_at`),
    session_id: randomUUID(),
    recording_source: CALIBRATION_TIMING_RECORDER_VERSION,
  };
}

export function stopCalibrationTimingPass(pass, { now } = {}) {
  if (!pass || pass.status !== 'in-progress') {
    fail('calibration timing pass must be started by the recorder', 'TIMING_PROVENANCE_REQUIRED');
  }
  requireUuidSessionId(pass.session_id, `${pass.id}.session_id`);
  if (pass.recording_source !== CALIBRATION_TIMING_RECORDER_VERSION) {
    fail(`${pass.id} was not started by the timing recorder`, 'TIMING_PROVENANCE_REQUIRED');
  }
  const completedAt = calibrationTimestamp(now, `${pass.id}.completed_at`);
  if (Date.parse(completedAt) < Date.parse(pass.started_at)) {
    fail(`${pass.id} stop precedes its start`, 'TIMING_ORDER');
  }
  const elapsedSeconds = (Date.parse(completedAt) - Date.parse(pass.started_at)) / 1000;
  return {
    ...pass,
    status: 'complete',
    completed_at: completedAt,
    wall_clock_seconds: elapsedSeconds,
    editor_seconds: elapsedSeconds,
  };
}

export function recordCalibrationTiming({
  processedStartCount = 20,
  now,
  recorderCommand = CALIBRATION_TIMING_RECORDING_COMMAND,
} = {}) {
  if (!Number.isInteger(processedStartCount) || processedStartCount < 1) {
    fail('processedStartCount must be a positive integer', 'INVALID_TIMING_DENOMINATOR');
  }
  if (recorderCommand !== CALIBRATION_TIMING_RECORDING_COMMAND) {
    fail('calibration timing must be recorded by the calibration timing command', 'TIMING_PROVENANCE_REQUIRED');
  }
  const sessionId = randomUUID();
  const passes = CALIBRATION_TIMING_PASS_IDS.map((passId) => (
    stopCalibrationTimingPass(startCalibrationTimingPass({ passId, now }), { now })
  ));
  const recording = finishCalibrationTimingRecording({
    processedStartCount,
    recorderCommand,
    passes,
    sessionId,
  });
  return recording;
}

export async function recordCalibrationTimingSession({
  processedStartCount = 20,
  passDurationMs = 1000,
  recorderCommand = CALIBRATION_TIMING_RECORDING_COMMAND,
} = {}) {
  if (!Number.isInteger(passDurationMs) || passDurationMs < 0 || passDurationMs > 60000) {
    fail('passDurationMs must be an integer between 0 and 60000', 'INVALID_TIMING_DURATION');
  }
  if (recorderCommand !== CALIBRATION_TIMING_RECORDING_COMMAND) {
    fail('calibration timing must be recorded by the calibration timing command', 'TIMING_PROVENANCE_REQUIRED');
  }
  const passes = [];
  for (const passId of CALIBRATION_TIMING_PASS_IDS) {
    const started = startCalibrationTimingPass({ passId });
    await new Promise((resolve) => setTimeout(resolve, passDurationMs));
    passes.push(stopCalibrationTimingPass(started));
  }
  return finishCalibrationTimingRecording({
    processedStartCount,
    recorderCommand,
    passes,
  });
}

export function verifyCalibrationTimingRecording(recording) {
  if (!recording || typeof recording !== 'object') {
    fail('calibration timing recording must be an object', 'TIMING_PROVENANCE_REQUIRED');
  }
  if (recording.recorder_version !== CALIBRATION_TIMING_RECORDER_VERSION
    || recording.recording_source !== CALIBRATION_TIMING_RECORDER_VERSION
    || recording.recorder_command !== CALIBRATION_TIMING_RECORDING_COMMAND
    || recording.clock_source !== 'system-clock') {
    fail('calibration timing recording does not identify the timing recorder', 'TIMING_PROVENANCE_REQUIRED');
  }
  requireUuidSessionId(recording.session_id, 'calibration timing session_id');
  requireFeedbackTimestamp(recording.recorded_at);
  if (!Number.isInteger(recording.processed_start_count) || recording.processed_start_count < 1) {
    fail('calibration timing recording has an invalid processed-start denominator', 'TIMING_DENOMINATOR_INVALID');
  }
  if (!Array.isArray(recording.passes)
    || JSON.stringify(recording.passes.map(({ id }) => id)) !== JSON.stringify(CALIBRATION_TIMING_PASS_IDS)) {
    fail('calibration timing recording pass coverage drifted', 'TIMING_PASS_COVERAGE');
  }
  const sessionIds = new Set();
  let editorSeconds = 0;
  for (const pass of recording.passes) {
    requireUuidSessionId(pass.session_id, `${pass.id}.session_id`);
    if (sessionIds.has(pass.session_id)) fail('calibration timing pass sessions must be unique', 'TIMING_PROVENANCE_REQUIRED');
    sessionIds.add(pass.session_id);
    if (pass.status !== 'complete' || pass.recording_source !== CALIBRATION_TIMING_RECORDER_VERSION) {
      fail(`${pass.id} is not a complete recorder pass`, 'TIMING_PROVENANCE_REQUIRED');
    }
    requireFeedbackTimestamp(pass.started_at);
    requireFeedbackTimestamp(pass.completed_at);
    const elapsedSeconds = (Date.parse(pass.completed_at) - Date.parse(pass.started_at)) / 1000;
    if (pass.wall_clock_seconds !== elapsedSeconds || pass.editor_seconds !== elapsedSeconds) {
      fail(`${pass.id} duration does not match recorder timestamps`, 'TIMING_DURATION_DRIFT');
    }
    editorSeconds += pass.editor_seconds;
  }
  if (recording.recording_proof_sha256 !== calibrationTimingProof(recording)) {
    fail('calibration timing recording proof does not match recorder output', 'TIMING_RECORDING_PROOF_MISMATCH');
  }
  return {
    status: 'complete',
    processed_start_count: recording.processed_start_count,
    editor_seconds: editorSeconds,
    editor_seconds_per_processed_start: editorSeconds / recording.processed_start_count,
    unmeasured_pass_count: 0,
    pass_count: recording.passes.length,
  };
}

function timingContractVersion(manifest) {
  return manifest.sense_review?.preflight?.process_revision === M5_10A_PROCESS_REVISION
    ? M5_10A_TIMING_CONTRACT_VERSION
    : LEGACY_TIMING_CONTRACT_VERSION;
}

function prepareRecorderManifest(manifest) {
  validateBatchManifest(manifest);
  const updated = structuredClone(manifest);
  updated.measurement.timing.contract_version = timingContractVersion(updated);
  updated.measurement.timing.passes = prepareLegacyFollowUpCycles(
    updated.measurement.timing.passes,
  );
  return updated;
}

function optionalPasses(manifest) {
  return manifest.measurement.timing.passes.filter(
    ({ id }) => OPTIONAL_PASS_IDS.includes(id),
  );
}

export function nextFeedbackCycle(manifest) {
  validateBatchManifest(manifest);
  const passes = optionalPasses(manifest);
  if (passes.length === 0) return 1;
  const cycles = passes.map((pass) => timingPassCycle(pass));
  return Math.max(...cycles) + 1;
}

function prepareLegacyFollowUpCycles(passes) {
  const followUps = passes.filter(
    ({ id }) => OPTIONAL_PASS_IDS.includes(id),
  );
  if (followUps.length === 0 || followUps.every((pass) => Object.hasOwn(pass, 'cycle'))) {
    return passes;
  }
  if (followUps.length !== 2 || followUps.some((pass) => Object.hasOwn(pass, 'cycle'))) {
    fail(
      'legacy follow-up timing must contain one complete audit/fixes pair before a new cycle is recorded',
      'INCOMPLETE_LEGACY_CYCLE',
    );
  }
  return passes.map((pass) => (
    followUps.includes(pass) ? { ...pass, cycle: 1 } : pass
  ));
}

export function appendFeedbackCycle(
  manifest,
  {
    feedbackReceivedAt,
    now,
    auditNote = 'PR feedback cycle audit is awaiting actual start/stop measurement.',
    fixesNote = 'PR feedback cycle fixes are awaiting actual start/stop measurement.',
  } = {},
) {
  validateBatchManifest(manifest);
  const feedbackTimestamp = feedbackReceivedAt === undefined
    ? timestampFromClock(now, 'feedback event')
    : feedbackReceivedAt;
  requireFeedbackTimestamp(feedbackTimestamp);
  if (typeof auditNote !== 'string' || auditNote.trim().length === 0) {
    fail('auditNote must be a non-empty string', 'INVALID_NOTE');
  }
  if (typeof fixesNote !== 'string' || fixesNote.trim().length === 0) {
    fail('fixesNote must be a non-empty string', 'INVALID_NOTE');
  }

  const preparedPasses = prepareLegacyFollowUpCycles(
    manifest.measurement.timing.passes.map((pass) => structuredClone(pass)),
  );
  const cycle = preparedPasses.length === 0
    ? 1
    : Math.max(
      0,
      ...preparedPasses
        .filter(({ id }) => id === 'post-review-audit' || id === 'post-review-fixes')
        .map((pass) => timingPassCycle(pass)),
    ) + 1;
  const followUp = [
    {
      id: 'post-review-audit',
      cycle,
      feedback_received_at: feedbackTimestamp,
      status: 'unmeasured',
      note: auditNote,
    },
    {
      id: 'post-review-fixes',
      cycle,
      feedback_received_at: feedbackTimestamp,
      status: 'unmeasured',
      note: fixesNote,
    },
  ];
  const updated = structuredClone(manifest);
  updated.measurement.timing.contract_version = timingContractVersion(updated);
  updated.measurement.timing.status = 'incomplete';
  updated.measurement.timing.passes = [...preparedPasses, ...followUp];
  validateBatchManifest(updated);
  return updated;
}

function passLabel(pass) {
  return Object.hasOwn(pass, 'cycle') ? `${pass.id}#${pass.cycle}` : pass.id;
}

function parseCycle(cycle) {
  if (cycle === undefined) return undefined;
  const value = Number(cycle);
  if (!Number.isInteger(value) || value < 1) {
    fail('cycle must be a positive integer', 'INVALID_TIMING_CYCLE');
  }
  return value;
}

function followUpPassesByCycle(passes) {
  const byCycle = new Map();
  for (const pass of passes.filter(({ id }) => OPTIONAL_PASS_IDS.includes(id))) {
    const cycle = timingPassCycle(pass);
    if (!byCycle.has(cycle)) byCycle.set(cycle, {});
    byCycle.get(cycle)[pass.id] = pass;
  }
  return byCycle;
}

function latestFollowUpCycle(passes) {
  const cycles = [...followUpPassesByCycle(passes).keys()];
  return cycles.length === 0 ? undefined : Math.max(...cycles);
}

function findRequiredPass(passes, passId) {
  return passes.find((pass) => pass.id === passId && !Object.hasOwn(pass, 'cycle'));
}

function findFollowUpPass(passes, passId, cycle) {
  const matches = passes.filter((pass) => (
    pass.id === passId
      && (cycle === undefined || timingPassCycle(pass) === cycle)
  ));
  if (matches.length === 0) return undefined;
  if (matches.length > 1) {
    fail(`timing pass ${passId} requires an explicit cycle`, 'AMBIGUOUS_TIMING_PASS');
  }
  return matches[0];
}

function ensureFeedbackCycleForAudit(manifest, startedAt) {
  const passes = manifest.measurement.timing.passes;
  const latestCycle = latestFollowUpCycle(passes);
  if (latestCycle === undefined) {
    return appendFeedbackCycle(manifest, { feedbackReceivedAt: startedAt });
  }

  const latest = followUpPassesByCycle(passes).get(latestCycle);
  const auditPass = latest['post-review-audit'];
  const fixesPass = latest['post-review-fixes'];
  if (!auditPass || !fixesPass) {
    fail(`timing feedback cycle ${latestCycle} is incomplete`, 'INCOMPLETE_TIMING_CYCLE');
  }
  if (auditPass.status === 'in-progress') {
    fail(`timing pass ${passLabel(auditPass)} is already running`, 'DUPLICATE_TIMING_START');
  }
  if (fixesPass.status === 'in-progress') {
    fail(`timing pass ${passLabel(fixesPass)} is already running`, 'INCOMPLETE_TIMING_CYCLE');
  }
  if (auditPass.status === 'complete') {
    if (fixesPass.status !== 'complete') {
      fail(
        `timing feedback cycle ${latestCycle} must finish its fixes before a new audit starts`,
        'INCOMPLETE_TIMING_CYCLE',
      );
    }
    return appendFeedbackCycle(manifest, { feedbackReceivedAt: startedAt });
  }
  if (fixesPass.status === 'complete') {
    fail(
      `timing feedback cycle ${latestCycle} has complete fixes but no complete audit`,
      'INCOMPLETE_TIMING_CYCLE',
    );
  }
  return manifest;
}

function timingStatusAfterStop(passes) {
  return passes.every(({ status }) => status === 'complete') ? 'complete' : 'incomplete';
}

export function startTimingPass(
  manifest,
  {
    passId,
    now,
    sessionId,
  } = {},
) {
  requirePassId(passId);
  const startedAt = timestampFromClock(now, 'started_at');
  let updated = prepareRecorderManifest(manifest);

  if (passId === 'post-review-audit') {
    updated = ensureFeedbackCycleForAudit(updated, startedAt);
  }

  const cycle = OPTIONAL_PASS_IDS.includes(passId)
    ? latestFollowUpCycle(updated.measurement.timing.passes)
    : undefined;
  if (passId === 'post-review-fixes' && cycle === undefined) {
    fail('post-review-fixes cannot start before a feedback event creates a cycle', 'MISSING_TIMING_CYCLE');
  }

  const pass = OPTIONAL_PASS_IDS.includes(passId)
    ? findFollowUpPass(updated.measurement.timing.passes, passId, cycle)
    : findRequiredPass(updated.measurement.timing.passes, passId);
  if (!pass) fail(`timing pass ${passId} does not exist`, 'MISSING_TIMING_PASS');
  if (pass.status === 'in-progress') {
    fail(`timing pass ${passLabel(pass)} is already running`, 'DUPLICATE_TIMING_START');
  }
  if (pass.status !== 'unmeasured') {
    fail(`timing pass ${passLabel(pass)} is already recorded`, 'TIMING_PASS_ALREADY_RECORDED');
  }
  if (passId === 'post-review-fixes') {
    const auditPass = findFollowUpPass(
      updated.measurement.timing.passes,
      'post-review-audit',
      cycle,
    );
    if (!auditPass || auditPass.status !== 'complete') {
      fail(
        `timing feedback cycle ${cycle} audit must finish before fixes start`,
        'TIMING_ORDER',
      );
    }
  }

  pass.status = 'in-progress';
  pass.started_at = startedAt;
  pass.session_id = requireSessionId(sessionId);
  pass.recording_source = TIMING_RECORDER_SOURCE;
  updated.measurement.timing.status = 'incomplete';
  validateBatchManifest(updated);
  return updated;
}

export function stopTimingPass(
  manifest,
  {
    passId,
    cycle,
    now,
  } = {},
) {
  requirePassId(passId);
  const stopAt = timestampFromClock(now, 'completed_at');
  const normalizedCycle = OPTIONAL_PASS_IDS.includes(passId) ? parseCycle(cycle) : undefined;
  const updated = prepareRecorderManifest(manifest);
  const passes = updated.measurement.timing.passes;
  const pass = OPTIONAL_PASS_IDS.includes(passId)
    ? findFollowUpPass(passes, passId, normalizedCycle)
    : findRequiredPass(passes, passId);
  if (!pass) {
    fail(`timing pass ${passId} has no active start`, 'TIMING_NOT_STARTED');
  }
  if (pass.status === 'complete') {
    fail(`timing pass ${passLabel(pass)} has already stopped`, 'DUPLICATE_TIMING_STOP');
  }
  if (pass.status !== 'in-progress') {
    fail(`timing pass ${passLabel(pass)} has no active start`, 'TIMING_NOT_STARTED');
  }
  if (pass.recording_source !== TIMING_RECORDER_SOURCE || !pass.session_id) {
    fail(
      `timing pass ${passLabel(pass)} was not started by the timing recorder`,
      'TIMING_PROVENANCE_REQUIRED',
    );
  }
  if (Date.parse(stopAt) < Date.parse(pass.started_at)) {
    fail(`timing pass ${passLabel(pass)} stop precedes its start`, 'TIMING_ORDER');
  }
  const elapsedSeconds = (Date.parse(stopAt) - Date.parse(pass.started_at)) / 1000;
  pass.status = 'complete';
  pass.completed_at = stopAt;
  pass.wall_clock_seconds = elapsedSeconds;
  pass.editor_seconds = elapsedSeconds;
  updated.measurement.timing.status = timingStatusAfterStop(passes);
  validateBatchManifest(updated);
  return updated;
}

async function readJson(filePath) {
  try {
    return JSON.parse(await readFile(filePath, 'utf8'));
  } catch (error) {
    if (error.code === 'ENOENT') fail(`manifest does not exist: ${filePath}`, 'MISSING_MANIFEST');
    if (error instanceof SyntaxError) fail(`manifest is not valid JSON: ${error.message}`, 'INVALID_JSON');
    throw error;
  }
}

function parseArguments(argv) {
  const args = {};
  for (const argument of argv) {
    if (!argument.startsWith('--') || !argument.includes('=')) {
      fail(`arguments must use --name=value form (received ${argument})`, 'INVALID_ARGUMENT');
    }
    const separator = argument.indexOf('=');
    args[argument.slice(2, separator)] = argument.slice(separator + 1);
  }
  return args;
}

export async function main(argv = process.argv.slice(2)) {
  const args = parseArguments(argv);
  if (!args.manifest || !args.output) {
    fail('--manifest and --output are required', 'MISSING_ARGUMENT');
  }
  for (const forbidden of [
    'feedback-received-at',
    'started-at',
    'completed-at',
    'wall-clock-seconds',
    'editor-seconds',
    'now',
  ]) {
    if (Object.hasOwn(args, forbidden)) {
      fail(`--${forbidden} is not accepted; the timing recorder uses its current clock`, 'MANUAL_TIMING_INPUT');
    }
  }
  const manifestPath = path.resolve(args.manifest);
  const outputPath = path.resolve(args.output);
  const manifest = await readJson(manifestPath);
  const action = args.action ?? 'feedback';
  let updated;
  if (action === 'feedback') {
    updated = appendFeedbackCycle(manifest, {
      now: new Date(),
      auditNote: args['audit-note'],
      fixesNote: args['fixes-note'],
    });
  } else if (action === 'start') {
    if (!args.pass) fail('--pass is required for a start action', 'MISSING_ARGUMENT');
    updated = startTimingPass(manifest, { passId: args.pass });
  } else if (action === 'stop') {
    if (!args.pass) fail('--pass is required for a stop action', 'MISSING_ARGUMENT');
    updated = stopTimingPass(manifest, { passId: args.pass, cycle: args.cycle });
  } else {
    fail(`unknown timing action ${action}`, 'INVALID_ACTION');
  }
  await writeFile(outputPath, `${JSON.stringify(updated, null, 2)}\n`, 'utf8');
  const message = action === 'feedback'
    ? `Recorded feedback cycle ${nextFeedbackCycle(manifest)}`
    : `${action === 'start' ? 'Started' : 'Stopped'} timing pass ${args.pass}`;
  console.log(`${message} for ${path.relative(REPOSITORY_DIRECTORY, manifestPath)}.`);
  return updated;
}

const isMainModule =
  process.argv[1]
  && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url));

if (isMainModule) {
  main().catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
